# Generated by Django 2.2.10 on 2021-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['answer'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_text'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk'], 'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='api.Answer', verbose_name='Ответ, ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.BooleanField(blank=True, null=True, verbose_name='Тип вопроса(неизвестно-ответ вручную, нет-один ответ, да-несколько ответов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(related_name='users', to='api.Question', verbose_name='Вопросы'),
        ),
    ]
