# Generated by Django 2.2.10 on 2021-03-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210304_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surveys',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
