# Generated by Django 2.2.10 on 2021-03-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210304_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='surveys',
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(related_name='surveys', to='api.Question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
    ]
