# Generated by Django 2.2.10 on 2021-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя пользователя'),
        ),
    ]
