# Generated by Django 2.2.10 on 2021-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210304_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Имя пользователя'),
        ),
    ]
