# Generated by Django 2.2.10 on 2021-03-04 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['pk'], 'verbose_name': 'Ответ Пользователя', 'verbose_name_plural': 'Ответы Пользователей'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_end',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата старта опроса'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='api.Survey', verbose_name='Опросник'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.User', verbose_name='ID Пользователя'),
        ),
    ]
