# Generated by Django 2.2.10 on 2021-03-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210305_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateTimeField(db_index=True, verbose_name='Дата старта опроса'),
        ),
    ]
