# Generated by Django 2.2.10 on 2021-03-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210305_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='api.Answer', verbose_name='Ответы'),
        ),
    ]
