# Generated by Django 2.2.10 on 2021-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210306_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='', verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
