# Generated by Django 2.2.10 on 2021-03-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210307_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='api.Question', verbose_name='Вопросы'),
        ),
    ]
