# Generated by Django 2.2.10 on 2021-03-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210307_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='api.Answer', verbose_name='Ответы'),
            preserve_default=False,
        ),
    ]
