# Generated by Django 2.2.10 on 2021-03-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210307_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='api.Answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Тип вопроса(None-вручную, False-один ответ, True-несколько ответов'),
        ),
    ]
