# Generated by Django 2.2.10 on 2021-03-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210307_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='questions', to='api.Answer', verbose_name='Ответы'),
        ),
    ]
