# Generated by Django 2.2.10 on 2021-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210307_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=None, verbose_name='Ответ'),
        ),
    ]
