# Generated by Django 3.1.7 on 2021-03-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210307_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('name',)},
        ),
    ]
