# Generated by Django 3.1.7 on 2021-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210311_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['pk'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['pk'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(default=None, related_name='questions', to='api.Answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=None, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('0', 'Свой ответ'), ('1', 'Выбор одного ответа'), ('2', 'Выбор нескольких ответов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_end',
            field=models.DateTimeField(db_index=True, default=None, verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание опроса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together=set(),
        ),
    ]
