# Generated by Django 2.2.10 on 2021-03-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210311_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='api.Answer', verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
