# Generated by Django 2.2.10 on 2021-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210312_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='type_question',
        ),
        migrations.AddField(
            model_name='question',
            name='type_answer',
            field=models.CharField(choices=[('0', 'Свой ответ'), ('1', 'Выбор одного ответа'), ('2', 'Выбор нескольких ответов')], default='0', max_length=1, verbose_name='Тип ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, default=None, related_name='questions', to='api.Answer', verbose_name='Ответы'),
        ),
    ]
