# Generated by Django 2.2.10 on 2021-03-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210320_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(default=None, related_name='questions', to='api.Answer', verbose_name='Ответы'),
        ),
    ]
