# Generated by Django 2.2.10 on 2021-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210321_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, default=None, related_name='questions', to='api.Answer', verbose_name='Ответы'),
        ),
    ]
